# Configuration for SwiftLint (https://github.com/realm/SwiftLint)

excluded:
  - Carthage
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - first_where
#  - missing_docs
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - vertical_whitespace
disabled_rules:
  - colon
  - comma
  - cyclomatic_complexity
  - function_body_length
  - syntactic_sugar
  - valid_docs

trailing_comma:
  mandatory_comma: true

line_length:
  warning: 120
