# Configuration for SwiftLint (https://github.com/realm/SwiftLint)

excluded:
  - Carthage
disabled_rules:
 - cyclomatic_complexity
 - function_body_length
 - line_length
 - opening_brace
 - valid_docs
