# Configuration for SwiftLint (https://github.com/realm/SwiftLint)

excluded:
  - Carthage
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - first_where
  - missing_docs
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - vertical_whitespace
disabled_rules:
  - closure_parameter_position
  - colon
  - comma
  - cyclomatic_complexity
  - function_body_length
  - line_length
  - opening_brace
  - syntactic_sugar
  - trailing_comma
  - unused_closure_parameter
  - valid_docs
  - vertical_parameter_alignment
