# Configuration for Travis (https://travis-ci.org)

language: objective-c

xcode_workspace: OneTimePassword.xcworkspace
xcode_scheme: OneTimePassword

osx_image: xcode8
xcode_sdk: iphonesimulator10.0

env:
  - DESTINATION="OS=10.0,name=iPhone 5"
  - DESTINATION="OS=10.0,name=iPhone 6S Plus"
  - DESTINATION="OS=10.0,name=iPhone SE"
  - DESTINATION="OS=10.0,name=iPad Retina"
  - DESTINATION="OS=10.0,name=iPad Pro (12.9-inch)"

# Check out nested dependencies
before_install: git submodule update --init --recursive

# A custom test script is required because xctool cannot access the iOS keychain
# https://github.com/facebook/xctool/issues/269
script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -destination "$DESTINATION" build test | xcpretty -c
