# Configuration for Travis (https://travis-ci.org)

language: objective-c

xcode_workspace: OneTimePassword.xcworkspace
xcode_scheme: OneTimePassword (iOS)

osx_image: xcode12.4

env:
  - RUNTIME="iOS 9.0" DEVICE="iPhone 4s"
  - RUNTIME="iOS 10.3" DEVICE="iPhone 5s"
  - RUNTIME="iOS 11.4" DEVICE="iPhone X"
  - RUNTIME="iOS 12.4" DEVICE="iPhone XS Max"
  - RUNTIME="iOS 13.7" DEVICE="iPhone 11"
  - RUNTIME="iOS 14.3" DEVICE="iPhone 12 Mini"

# Include builds for watchOS
matrix:
  include:
    # Build and test with Xcode 10.2 to ensure Swift 5.0 support.
    - &xcode10.2
      osx_image: xcode10.2
      env: RUNTIME="iOS 12.2" DEVICE="iPhone 4s"

    # Include several build-only jobs for watchOS
    - &watchos
      xcode_scheme: OneTimePassword (watchOS)
      # The newest runtime and device:
      env: BUILD_ONLY="YES" RUNTIME="watchOS 7.2" DEVICE="Apple Watch Series 6 - 44mm"
    - <<: *watchos
      # The oldest supported runtime and device:
      env: BUILD_ONLY="YES" RUNTIME="watchOS 2.0" DEVICE="Apple Watch - 38mm"
    - <<: *watchos
      osx_image: xcode10.2
      # The newest device an runtime supported by Xcode 10.2:
      env: BUILD_ONLY="YES" RUNTIME="watchOS 5.2" DEVICE="Apple Watch Series 4 - 44mm"

    # Build with Carthage
    - &carthage
      env:
      before_script:
      script: carthage build --no-skip-current

    # Build with CocoaPods
    - &cocoapods
      env:
      before_script:
      script: pod lib lint --allow-warnings --verbose

before_script:
  - DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
  - RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
  - DESTINATION_ID=$(xcrun simctl create Travis $DEVICE_ID $RUNTIME_ID)
  - xcrun simctl boot $DESTINATION_ID
  - if [[ $BUILD_ONLY == YES ]]; then ACTIONS="build"; else ACTIONS="build-for-testing test-without-building"; fi
  - echo "xcodebuild -workspace \"$TRAVIS_XCODE_WORKSPACE\" -scheme \"$TRAVIS_XCODE_SCHEME\" -destination \"id=$DESTINATION_ID\" $ACTIONS"

script: set -o pipefail && xcodebuild -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -destination "id=$DESTINATION_ID" $ACTIONS | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
