language: objective-c

xcode_workspace: OneTimePassword.xcworkspace
xcode_scheme:
 - OneTimePassword
 - OneTimePasswordLegacy

osx_image: xcode6.4
xcode_sdk: iphonesimulator8.4

before_install:
 - git submodule update --init --recursive
script:
 - xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build test
 - xctool -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build test
