language: objective-c

xcode_workspace: OneTimePassword.xcworkspace
xcode_scheme:
 - OneTimePassword
 - OneTimePasswordLegacy

osx_image: xcode7
xcode_sdk:
 - iphonesimulator9.0

# Check out nested dependencies
before_install: git submodule update --init --recursive

# A custom test script is required because xctool cannot access the iOS keychain
# https://github.com/facebook/xctool/issues/269
script: xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build test | xcpretty -c
