# Configuration for Travis (https://travis-ci.org)

language: objective-c

xcode_workspace: OneTimePassword.xcworkspace
xcode_scheme: OneTimePassword (iOS)

osx_image: xcode8.2
xcode_sdk: iphonesimulator10.2

env:
  - RUNTIME="iOS 8.1"  DEVICE="iPad 2"
  - RUNTIME="iOS 8.2"  DEVICE="iPhone 4s"
  - RUNTIME="iOS 8.3"  DEVICE="iPhone 5"
  - RUNTIME="iOS 8.4"  DEVICE="iPhone 5s"
  - RUNTIME="iOS 9.0"  DEVICE="iPhone 6"
  - RUNTIME="iOS 9.1"  DEVICE="iPhone 6 Plus"
  - RUNTIME="iOS 9.2"  DEVICE="iPhone 6s"
  - RUNTIME="iOS 9.3"  DEVICE="iPhone 6s Plus"
  - RUNTIME="iOS 10.0" DEVICE="iPhone SE"
  - RUNTIME="iOS 10.1" DEVICE="iPhone 7"
  - RUNTIME="iOS 10.2" DEVICE="iPhone 7 Plus"

# Include builds for Xcode 8, Xcode 8.1, and Xcode 7.3 with Swift 2.2
matrix:
  include:
    - osx_image: xcode8.1
      xcode_sdk: iphonesimulator10.1
      env: RUNTIME="iOS 10.1" DEVICE="iPhone 7"
    - osx_image: xcode8
      xcode_sdk: iphonesimulator10.0
      env: RUNTIME="iOS 10.0" DEVICE="iPhone SE"
    - osx_image: xcode7.3
      xcode_sdk: iphonesimulator9.3
      env: RUNTIME="iOS 9.3" DEVICE="iPhone 6s Plus"
    - xcode_scheme: OneTimePassword (watchOS)
      xcode_sdk: watchsimulator3.1
      env: RUNTIME="watchOS 3.1" DEVICE="Apple Watch Series 2 - 42mm"
      script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme "$TRAVIS_XCODE_SCHEME" -sdk $TRAVIS_XCODE_SDK build | xcpretty -c
    - osx_image: xcode7.3
      xcode_scheme: OneTimePassword (watchOS)
      xcode_sdk: watchsimulator2.2
      env: RUNTIME="watchOS 2.2" DEVICE="Apple Watch - 38mm"
      script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme "$TRAVIS_XCODE_SCHEME" -sdk $TRAVIS_XCODE_SDK build | xcpretty -c


# Check out nested dependencies
before_install: git submodule update --init --recursive

before_script:
  - DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
  - RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
  - DESTINATION_ID=$(xcrun simctl create Travis $DEVICE_ID $RUNTIME_ID)
  - xcrun simctl boot $DESTINATION_ID

script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme "$TRAVIS_XCODE_SCHEME" -sdk $TRAVIS_XCODE_SDK -destination "id=$DESTINATION_ID" build test | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
