# Configuration for Travis (https://travis-ci.org)

language: objective-c

xcode_workspace: OneTimePassword.xcworkspace
xcode_scheme: OneTimePassword (iOS)

osx_image: xcode8
xcode_sdk: iphonesimulator10.0

env:
  - DESTINATION="OS=9.0,name=iPhone 6"
  - DESTINATION="OS=9.1,name=iPhone 6 Plus"
  - DESTINATION="OS=9.2,name=iPhone 6S"
  - DESTINATION="OS=9.3,name=iPhone 6S Plus"
  - DESTINATION="OS=10.0,name=iPhone 7"

# For now, continue testing with Xcode 7.3 and Swift 2.2
# Testing on iOS 8.x currently times out on Travis with Xcode 8:
# https://travis-ci.org/mattrubin/OneTimePassword/jobs/160929197
matrix:
  include:
    - osx_image: xcode7.3
      xcode_sdk: iphonesimulator9.3
      env: DESTINATION="OS=8.1,name=iPhone 4S"
    - osx_image: xcode7.3
      xcode_sdk: iphonesimulator9.3
      env: DESTINATION="OS=8.2,name=iPhone 5"
    - osx_image: xcode7.3
      xcode_sdk: iphonesimulator9.3
      env: DESTINATION="OS=8.3,name=iPhone 5S"
    - osx_image: xcode7.3
      xcode_sdk: iphonesimulator9.3
      env: DESTINATION="OS=8.4,name=iPhone 6"

# Check out nested dependencies
before_install: git submodule update --init --recursive

# A custom test script is required because xctool cannot access the iOS keychain
# https://github.com/facebook/xctool/issues/269
script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -destination "$DESTINATION" build test | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
