# Configuration for Travis (https://travis-ci.org)

language: objective-c

xcode_workspace: OneTimePassword.xcworkspace
xcode_scheme: OneTimePassword (iOS)

osx_image: xcode8
xcode_sdk: iphonesimulator10.0

env:
# iOS 8 builds time out with Xcode 8
#  - DESTINATION="OS=8.1,name=iPhone 4S"
#  - DESTINATION="OS=8.2,name=iPhone 5"
#  - DESTINATION="OS=8.3,name=iPhone 5S"
#  - DESTINATION="OS=8.4,name=iPhone 6"
  - DESTINATION="OS=9.0,name=iPhone 6"
  - DESTINATION="OS=9.1,name=iPhone 6 Plus"
  - DESTINATION="OS=9.2,name=iPhone 6S"
  - DESTINATION="OS=9.3,name=iPhone 6S Plus"
  - DESTINATION="OS=10.0,name=iPhone 7"

matrix:
  include:
    - xcode_scheme: OneTimePassword (watchOS)
      xcode_sdk: watchsimulator3.0
      script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme "$TRAVIS_XCODE_SCHEME" -sdk $TRAVIS_XCODE_SDK build | xcpretty -c
    - osx_image: xcode7.3
      xcode_scheme: OneTimePassword (watchOS)
      xcode_sdk: watchsimulator2.2
      script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme "$TRAVIS_XCODE_SCHEME" -sdk $TRAVIS_XCODE_SDK build | xcpretty -c

# Check out nested dependencies
before_install: git submodule update --init --recursive

script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme "$TRAVIS_XCODE_SCHEME" -sdk $TRAVIS_XCODE_SDK -destination "$DESTINATION" build test | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
