language: objective-c

xcode_workspace: onetimepassword.xcworkspace
xcode_scheme:
- OneTimePassword
- OneTimePasswordLegacy
xcode_sdk:
- iphonesimulator8.1

script: xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build test
