language: objective-c

xcode_workspace: onetimepassword.xcworkspace
xcode_scheme:
- OneTimePassword
- OneTimePasswordLegacy
xcode_sdk:
- iphonesimulator8.1

script:
- xcodebuild -workspace onetimepassword.xcworkspace -scheme OneTimePassword -sdk iphonesimulator8.1 build test
- xcodebuild -workspace onetimepassword.xcworkspace -scheme OneTimePasswordLegacy -sdk iphonesimulator8.1 build test
