language: objective-c

xcode_workspace: onetimepassword.xcworkspace
xcode_scheme:
 - OneTimePassword
 - OneTimePasswordLegacy

osx_image: xcode7
xcode_sdk:
 - iphonesimulator9.0

before_install: git submodule update --init --recursive
