name: "Select Xcode version"
description: "Selects the specified version of Xcode"
inputs:
  version:
    description: "Version number"
    required: true
runs:
  using: composite
  steps:
    - name: "Select Xcode ${{ inputs.version }}" 
      run: sudo xcode-select -s /Applications/Xcode_${{ inputs.version }}.app
      shell: bash
    - name: "Print SDK info"
      run: xcodebuild -version -sdk
      shell: bash
    - name: "Print simulator info"
      run: xcrun simctl list
      shell: bash
