name: CI

on: [push]

jobs:
  xcode-ios:
    name: "Xcode / iOS"
    runs-on: macOS-10.15
    strategy:
      matrix:
        env:
          - xcode: 12.4
            runtime: "iOS 14.4"
            device: "iPhone 12 Pro Max"
          - xcode: 11.7
            runtime: "iOS 13.7"
            device: "iPhone 6s"
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: 'Select Xcode ${{ matrix.env.xcode }}'
      run: |
        sudo xcode-select -s /Applications/Xcode_${{ matrix.env.xcode }}.app
        xcodebuild -version -sdk
        xcrun simctl list
    - name: "Build and Test"
      run: |
        RUNTIME="${{ matrix.env.runtime }}"
        DEVICE="${{ matrix.env.device }}"
        DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        DESTINATION_ID=$(xcrun simctl create Travis $DEVICE_ID $RUNTIME_ID)
        xcrun simctl boot $DESTINATION_ID
        set -o pipefail
        xcodebuild test -workspace "OneTimePassword.xcworkspace" -scheme "OneTimePassword (iOS)" -destination "id=$DESTINATION_ID" | xcpretty -c

  carthage:
    name: "Carthage"
    runs-on: macOS-10.15
    strategy:
      matrix:
        env:
          - xcode: 12.4
          - xcode: 11.7
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: 'Select Xcode ${{ matrix.env.xcode }}'
      run: |
        sudo xcode-select -s /Applications/Xcode_${{ matrix.env.xcode }}.app
    - name: "Build"
      run: carthage build --archive --use-xcframeworks
