name: SPM

on: [push]

jobs:
  spm:
    name: "Xcode ${{ matrix.env.xcode }}"
    runs-on: macOS-10.15
    strategy:
      matrix:
        env:
          - xcode: 12.4
    steps:
    - uses: actions/checkout@v2
    - name: "Select Xcode ${{ matrix.env.xcode }}"
      uses: ./.github/actions/xcode-select
      with: 
        version: ${{ matrix.env.xcode }}
    - run: swift test
