name: CI

on: [push]

jobs:
  xcodebuild-swift-5-ios:
    name: "xcodebuild, Xcode 10.3, iOS"
    runs-on: macOS-10.14
    strategy:
      matrix:
        env:
          - RUNTIME="iOS 10.0" DEVICE="iPhone SE"
          - RUNTIME="iOS 10.2" DEVICE="iPhone 7 Plus"
          - RUNTIME="iOS 12.4" DEVICE="iPhone XS Max"
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: 'Select Xcode 10.3'
      run: sudo xcode-select -s /Applications/Xcode_10.3.app
    - name: "Build and Test"
      run: |
        ${{ matrix.env }}
        DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        DESTINATION_ID=$(xcrun simctl create Travis $DEVICE_ID $RUNTIME_ID)
        xcrun simctl boot $DESTINATION_ID
        set -o pipefail
        xcodebuild test -workspace "OneTimePassword.xcworkspace" -scheme "OneTimePassword (iOS)" -destination "id=$DESTINATION_ID" | xcpretty -c
