name: Xcode

on: [push]

jobs:
  xcode-ios:
    name: "Xcode / iOS"
    runs-on: macOS-10.15
    strategy:
      matrix:
        env:
          - xcode: 12.4
            ios: 14.4
          - xcode: 11.7
            ios: 13.7
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: 'Select Xcode ${{ matrix.env.xcode }}'
      run: |
        sudo xcode-select -s /Applications/Xcode_${{ matrix.env.xcode }}.app
        xcodebuild -version -sdk
        xcrun simctl list
    - name: "Build and Test"
      run: |
        set -o pipefail
        xcodebuild test -workspace "OneTimePassword.xcworkspace" -scheme "OneTimePassword (iOS)" -destination "platform=iOS Simulator,OS=${{ matrix.env.ios }}" | xcpretty -c
