name: Xcode

on: [push]

jobs:
  xcode-ios:
    name: "Xcode / iOS"
    runs-on: macOS-10.15
    strategy:
      matrix:
        env:
          - runtime: "iOS 14.4"
            device: "iPhone SE"
          - runtime: "iOS 14.4"
            device: "iPhone 7 Plus"
          - runtime: "iOS 14.4"
            device: "iPhone XS Max"
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: 'Select Xcode 12.4'
      run: |
        sudo xcode-select -s /Applications/Xcode_12.4.app
        xcodebuild -version -sdk
        xcrun simctl list
    - name: "Build and Test"
      run: |
        RUNTIME="${{ matrix.env.runtime }}"
        DEVICE="${{ matrix.env.device }}"
        DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        DESTINATION_ID=$(xcrun simctl create Travis $DEVICE_ID $RUNTIME_ID)
        xcrun simctl boot $DESTINATION_ID
        set -o pipefail
        xcodebuild test -workspace "OneTimePassword.xcworkspace" -scheme "OneTimePassword (iOS)" -destination "id=$DESTINATION_ID" | xcpretty -c
